# Generated by Django 5.1.7 on 2026-01-22 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('position', models.IntegerField(help_text='Position number of the airport', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('duration', models.IntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_routes', to='routes.airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='routes.airport')),
            ],
            options={
                'ordering': ['from_airport', 'direction'],
                'unique_together': {('from_airport', 'to_airport', 'direction')},
            },
        ),
    ]
